(import joy :prefix "")
(import ./layout :as layout)
(import ./routes :as routes)

(def db (env :db-name))

(def app (-> (app routes/app)
             (set-db db)
             (set-layout layout/app)
             (logger)
             (csrf-token)
             (session)
             (extra-methods)
             (query-string)
             (body-parser)
             (server-error)
             (x-headers)
             (static-files)))
